get http://localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMzAgRGF5cyBPZiBOb2RlLmpzIiwiZGF5IjoxMSwicGxhdGZvcm0iOiJzY2FsZXIiLCJ1c2VyIjoiYW5rdXJnYXR0YW5pIiwiaWF0IjoxNzA3NjczNzAwfQ.0_i3ZiZXxQG7MnaEiNMTIF9mOayd-Z1BwcApIMXUcns